const Legal = () => {
  return (
    <div className="flex flex-col gap-4 text-white text-sm font-light">
      <p>HARMONIX IS NOT AVAILABLE TO INDIVIDUALS FROM THE US AND OTHER SELECT COUNTRIES.</p>

      <p className="text-xs text-off-white opacity-90">
        RESIDENTS OF THE UNITED STATES ARE INELIGIBLE TO PARTICIPATE IN HARMONIX. IN ADDITION,
        RESIDENTS OF THE FOLLOWING COUNTRIES ARE ALSO INELIGIBLE: AFGHANISTAN, AUSTRALIA, BELGIUM,
        BELIZE, BOLIVIA, CANADA (PROVINCE OF QUEBEC), CAMBODIA, CHAD, CHINA, COLOMBIA, CUBA, IRAN,
        IRAQ, LEBANON, LIBYA, MYANMAR, NORTH KOREA, RUSSIA, SINGAPORE, SOMALIA, SUDAN, SYRIA,
        TANZANIA, THAILAND, TURKEY AND WHERE OTHERWISE PROHIBITED BY LAW. IF YOU ARE A RESIDENT OF
        ONE OF THESE COUNTRIES, DO NOT ENTER A JACKPOT, SINCE THE JACKPOTS ARE NOT INTENDED FOR YOU.
      </p>

      <p className="text-xs text-off-white opacity-90">
        YOU MUST BE 18 YEARS OR OLDER TO PARTICIPATE IN HARMONIX.
      </p>

      <p className="text-xs text-off-white opacity-90">
        RESIDENTS OF THESE COUNTRIES OR INDIVIDUALS PHYSICALLY LOCATED IN THESE COUNTRIES ARE
        PROHIBITED FROM COLLECTING ANY PAYOUTS. FOR THE AVOIDANCE OF DOUBT, USE OF THE SERVICES IS
        VOID WHERE PROHIBITED BY LAW.
      </p>

      <p className="text-xs text-off-white opacity-90 italic">
        HARMONIX RESERVES THE RIGHT, IN ITS SOLE DISCRETION, TO CONDITION THE AWARDING/DISTRIBUTION
        OF $EVERY UPON THE PASSING OF ITS KNOW YOUR CUSTOMER (“KYC”) PROCESS.
      </p>
    </div>
  );
};

export default Legal;
